export const PAKET_LIST = [
  {
    id: "PREMIUM_1BLN",
    nama: "Premium",
    durasi: "1 Bulan",
    harga: 49000,
    hargaPerBulan: 49000,
    color: "#1e3a8a",
    colorLight: "#dce1ff",
    popular: false,
    badge: null as string | null,
    fitur: [
      "Unlimited Tryout SKD CPNS",
      "Unlimited Tryout Kedinasan",
      "Unlimited Mini Tryout",
      "Analitik AI Personal",
      "Pembahasan Soal Lengkap",
      "Akses Bank Soal 10.000+",
      "Support via WhatsApp",
    ],
  },
  {
    id: "PREMIUM_3BLN",
    nama: "Premium Plus",
    durasi: "3 Bulan",
    harga: 119000,
    hargaPerBulan: Math.round(119000 / 3),
    color: "#7c3aed",
    colorLight: "#ede9fe",
    popular: true,
    badge: null as string | null,
    fitur: [
      "Hemat Rp 28.000 vs paket bulanan",
      "Unlimited Tryout SKD CPNS",
      "Unlimited Tryout Kedinasan",
      "Unlimited Mini Tryout",
      "Analitik AI Personal",
      "Pembahasan Soal Lengkap",
    ],
  },
  {
    id: "PREMIUM_6BLN",
    nama: "Premium Pro",
    durasi: "6 Bulan",
    harga: 199000,
    hargaPerBulan: Math.round(199000 / 6),
    color: "#b45309",
    colorLight: "#fef3c7",
    popular: false,
    badge: null as string | null,
    fitur: [
      "Hemat Rp 95.000 vs paket bulanan",
      "Unlimited Tryout SKD CPNS",
      "Unlimited Tryout Kedinasan",
      "Unlimited Mini Tryout",
      "Analitik AI Personal",
      "Pembahasan Soal Lengkap",
    ],
  },
  {
    id: "PREMIUM_1THN",
    nama: "Premium Pro Max",
    durasi: "1 Tahun",
    harga: 299000,
    hargaPerBulan: Math.round(299000 / 12),
    color: "#065f46",
    colorLight: "#d1fae5",
    popular: false,
    badge: "BEST VALUE 👑",
    fitur: [
      "Hemat Rp 289.000 vs paket bulanan",
      "Unlimited Tryout SKD CPNS",
      "Unlimited Tryout Kedinasan",
      "Unlimited Mini Tryout",
      "Analitik AI Personal",
      "Pembahasan Soal Lengkap",
    ],
  },
] as const;

export type PaketId = (typeof PAKET_LIST)[number]["id"];

export const formatRp = (n: number) => "Rp " + n.toLocaleString("id-ID");
